apiVersion: v1
kind: Service
metadata:
  name: envoy-front
spec:
  type: {{ .Values.envoy.service.type }}
  selector:
    app: envoy-front
  ports:
    - name: http
      port: {{ .Values.envoy.service.port }}
      targetPort: {{ .Values.envoy.service.targetPort }}
{{- if eq .Values.envoy.service.type "NodePort" }}
      nodePort: {{ .Values.envoy.service.nodePort }}
{{- end }}
