apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 10000
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    common_http_protocol_options:
                      max_requests_per_connection: {{ .Values.envoy.ddos.maxRequestsPerConnection }}
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: kong
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: kong_proxy
                    http_filters:
                      - name: envoy.filters.http.local_ratelimit
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                          stat_prefix: http_local_rate_limiter
                          token_bucket:
                            max_tokens: {{ .Values.envoy.ddos.localRateLimitPerMinute }}
                            tokens_per_fill: {{ .Values.envoy.ddos.localRateLimitPerMinute }}
                            fill_interval: 60s
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: kong_proxy
          type: LOGICAL_DNS
          connect_timeout: 1s
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: kong_proxy
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: kong-proxy.default.svc.cluster.local
                          port_value: 80
          circuit_breakers:
            thresholds:
              - max_connections: {{ .Values.envoy.ddos.maxConnections }}
                max_pending_requests: {{ .Values.envoy.ddos.maxPendingRequests }}
