apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-front
  labels:
    app: envoy-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-front
  template:
    metadata:
      labels:
        app: envoy-front
    spec:
      containers:
        - name: envoy
          image: "{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.tag }}"
          imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
          args:
            - "-c"
            - "/etc/envoy/envoy.yaml"
            - "--log-level"
            - "info"
          ports:
            - containerPort: 10000
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
