apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  labels:
    app: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: "{{ .Values.kong.image.repository }}:{{ .Values.kong.image.tag }}"
          imagePullPolicy: {{ .Values.kong.image.pullPolicy }}
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /kong_dbless/kong.yaml
            - name: KONG_PROXY_LISTEN
              value: 0.0.0.0:8000
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
            - name: KONG_LOG_LEVEL
              value: info
            - name: KONG_PLUGINS
              value: bundled,pre-function
          ports:
            - name: proxy
              containerPort: 8000
            - name: admin
              containerPort: 8001
          volumeMounts:
            - name: kong-config
              mountPath: /kong_dbless/kong.yaml
              subPath: kong.yaml
      volumes:
        - name: kong-config
          configMap:
            name: kong-dbless-config
